import {
  ShoppingBag,
  Utensils,
  Briefcase,
  Home,
  Heart,
  Car,
  Users,
  MoreHorizontal,
  Shirt,
  Armchair,
  Monitor,
  BookOpen,
  Sparkles,
  Trophy,
  Store,
  Coffee,
  Package,
  Cake,
  Beer,
  ShoppingCart,
  Truck,
  Scale,
  Calculator,
  Megaphone,
  Code,
  Lightbulb,
  Building,
  UserCheck,
  HardHat,
  Wrench,
  Zap,
  PaintBucket,
  Sparkle,
  Trees,
  Settings,
  Stethoscope,
  Activity,
  Dumbbell,
  Smile,
  Baby,
  Brain,
  Pill,
  KeyRound,
  Bike,
  CarTaxiFront,
  Replace,
  Move,
  Bus,
  GraduationCap,
  PartyPopper,
  Dog,
  Camera,
  Plane,
  HandHeart,
  Layers,
  Smartphone,
  Tv,
  Sofa,
  Gift,
  PawPrint,
  ChefHat,
  Hammer,
  SprayCan,
  Bug,
  Palette,
  Shield,
  UserPlus,
  Building2,
  HeartHandshake,
  Leaf,
  Languages,
  ClipboardCheck,
  Book,
  Music,
  Landmark,
  Puzzle,
  Key,
  Church,
  Calendar,
  LucideIcon,
} from "lucide-react";

// Map icon string keys to Lucide icon components
export const iconMap: Record<string, LucideIcon> = {
  // Parent category icons
  "shopping": ShoppingBag,
  "food": Utensils,
  "home": Home,
  "briefcase": Briefcase,
  "heart": Heart,
  "education": GraduationCap,
  "leisure": Trophy,
  "transport": Car,
  "family": Users,
  "community": HandHeart,
  "other": MoreHorizontal,
  
  // Subcategory icons
  "shirt": Shirt,
  "smartphone": Smartphone,
  "tv": Tv,
  "sofa": Sofa,
  "book-open": BookOpen,
  "gift": Gift,
  "sparkles": Sparkles,
  "dumbbell": Dumbbell,
  "paw-print": PawPrint,
  "utensils": Utensils,
  "coffee": Coffee,
  "package": Package,
  "cake": Cake,
  "beer": Beer,
  "chef-hat": ChefHat,
  "shopping-cart": ShoppingCart,
  "truck": Truck,
  "hard-hat": HardHat,
  "wrench": Wrench,
  "hammer": Hammer,
  "paint-bucket": PaintBucket,
  "trees": Trees,
  "spray-can": SprayCan,
  "bug": Bug,
  "scale": Scale,
  "calculator": Calculator,
  "monitor": Monitor,
  "palette": Palette,
  "users": Users,
  "shield": Shield,
  "user-plus": UserPlus,
  "building": Building,
  "stethoscope": Stethoscope,
  "smile": Smile,
  "brain": Brain,
  "heart-handshake": HeartHandshake,
  "activity": Activity,
  "pill": Pill,
  "leaf": Leaf,
  "graduation-cap": GraduationCap,
  "music": Music,
  "languages": Languages,
  "clipboard-check": ClipboardCheck,
  "book": Book,
  "trophy": Trophy,
  "landmark": Landmark,
  "puzzle": Puzzle,
  "car": Car,
  "user": Users,
  "car-taxi-front": CarTaxiFront,
  "bike": Bike,
  "key": Key,
  "bus": Bus,
  "baby": Baby,
  "dog": Dog,
  "party-popper": PartyPopper,
  "building-2": Building2,
  "church": Church,
  "hand-helping": HandHeart,
  "calendar": Calendar,
  "camera": Camera,
  "plane": Plane,
  "more-horizontal": MoreHorizontal,
  
  // Legacy/fallback mappings
  "armchair": Armchair,
  "store": Store,
  "megaphone": Megaphone,
  "code": Code,
  "lightbulb": Lightbulb,
  "user-check": UserCheck,
  "zap": Zap,
  "sparkle": Sparkle,
  "settings": Settings,
  "key-round": KeyRound,
  "replace": Replace,
  "move": Move,
  "layers": Layers,
};

/**
 * Get a Lucide icon component from a string key
 * Falls back to MoreHorizontal if not found
 */
export const getIcon = (iconKey: string | null | undefined): LucideIcon => {
  if (!iconKey) return MoreHorizontal;
  return iconMap[iconKey] || MoreHorizontal;
};
